# ===== Application =====
spring:
  data:
    redis:
      host: 192.168.220.134
      port: 6379
      password: 159357
      timeout: 5000
  application:
    name: studyhub

  # ===== Datasource (replace with your MySQL root password) =====
  datasource:
    url: jdbc:mysql://localhost:3306/studyhub?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# ===== Server Port =====
server:
  port: 8080

# ===== MyBatis-Plus =====
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ===== Knife4j =====
knife4j:
  enable: true

# ===== Logging =====
logging:
  level:
    com.studyhub: debug

#==== JWT ====
jwt:
  secret: studyhub-jwt-secret-key-must-be-at-least-32-chars!! #必须>=32字符
  expiration: 604800000 # 7天 毫秒